version: '2'
services:
  zookeeper:
    image: judetan/docker-ubuntu-openjdk8-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: judetan/docker-alpine-openjdk8-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "tweets:1:1,tweets_test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock